### ISSUE TITLE
server crashes at world creation

### ISSUE THREAD

**Issue by Nqndi** [Yukiiro-Nite/moon-generator#1]
Hi! Whenever I try to create a world with the multiverse command you provided, the server doesn't respond, then after a while, it crashes ( Timed out). Why?

**Comment by Nqndi** [comment]
Also, I am using 1.16.3 paper spigot

**Comment by Yukiiro-Nite** [comment]
Thanks for reaching out! Could you post a log file of when your server crashed?

**Comment by Nqndi** [comment]
[latest.log](https://github.com/Yukiiro-Nite/moon-generator/files/5453119/latest.log)

**Comment by Nqndi** [comment]
@Yukiiro-Nite

**Comment by Yukiiro-Nite** [comment]
@Nqndi it looks like your server timed out while generating craters. Sometimes generating craters causes new chunks to load, which in turn can make more craters generate. It looks like you had a bit of a run away generation problem.

As a quick fix, I'll add the ability to disable crater generation. (Pull request: https://github.com/Yukiiro-Nite/moon-generator/pull/2)
After that, I'll see what else I can do to prevent run away generation.

**Comment by Nqndi** [comment]
Alright! I'll download it as soon as it's up!

**Comment by Yukiiro-Nite** [comment]
@Nqndi Here's the new release: https://github.com/Yukiiro-Nite/moon-generator/releases/tag/1.0.1

I'd also recommend increasing the `max-tick-time` in server.properties. When testing the changes on my computer, my debug server still timed out with a 60 seconds `max-tick-time`. Even though my debug server did time out, when I restarted the server, the moon dimension was generating as expected.

Let me know if you have any more issues!
