### ISSUE TITLE
Server still crashing with craters turned off

### ISSUE THREAD

**Issue by Nqndi** [Yukiiro-Nite/moon-generator#3]
[latest.log](https://github.com/Yukiiro-Nite/moon-generator/files/5457249/latest.log)
Here is the log. I've turned off craters. I have a pretty good pc so it should ne able to generate it. Why?

**Comment by Yukiiro-Nite** [comment]
Can you tell me what your `max-tick-time`  and `view-distance` are set to in your server.properties? Does the server crash when you restart it?

**Comment by Nqndi** [comment]
I tried generating 5 times in a row, always crashed.
max-tick-time=60000
view-distance=10

**Comment by Yukiiro-Nite** [comment]
Could you try setting max-tick-time to 120000?
Also, does the world file for the moon exist after you use the `mv create` command?

**Comment by Nqndi** [comment]
I've set the max tick time to that, still nothing. The world although generates before the crash, at startup, it says that it is corrupted.

**Comment by Nqndi** [comment]
Can you try to reproduce the problem? Maybe we can figure out if there is something on my end.

**Comment by Yukiiro-Nite** [comment]
That sounds like a good idea, could you send me a zip of your server, that way I can run it locally?

When zipping the server up, you won't need to include the world files. Those shouldn't be important for debugging the issue.

**Comment by Yukiiro-Nite** [comment]
Maybe delete all the world files first, I won't need those.

**Comment by Nqndi** [comment]
I'll be home in a day, although I tried generating on a fresh New spigot 1.16.3 server, and it didn't work, so while im away you could try that.

**Comment by Yukiiro-Nite** [comment]
I was able to get the same problem to happen when using paper spigot 1.16.3. Locally I had been using normal spigot 1.16.1. This should help me debug what's going on.

**Comment by Yukiiro-Nite** [comment]
@Nqndi I've found a setup that works for paper spigot. Use release [1.0.2](https://github.com/Yukiiro-Nite/moon-generator/releases/tag/1.0.2) for this.

Add this to the bottom of your bukkit.yml:
```yaml
worlds:
  moon:
    generator: moon-generator
```
Change your server.properties:
```
level-name=moon
```

Now when you start the server, the moon world will be loaded as the default world. Unfortunately, the nether and the end will be generated for the moon as well, which I'm going to assume you don't want.

After the first generation finishes, you can run these commands to remove the extra worlds:
```
/mv remove moon_nether
/mv remove moon_the_end
```
Once the worlds have been removed from the multiverse config, you can delete those world folders.

Finally, change your server.properties `level-name` back to your default world, and start the server again.

**Comment by Yukiiro-Nite** [comment]
@Nqndi Were you able to get this working?

**Comment by Nqndi** [comment]
Oh yes I was, thanks btw, I forgot to reply.
